# .github/workflows/update_predictions.yml
name: Update Predictions

on:
  schedule:
    - cron: '0 12 * * *'  # Executa todo dia ao meio-dia UTC
  workflow_dispatch:  # Permite execução manual

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Run update script
      run: python update_predictions.py
      
    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add data/latest_predictions.csv
        git commit -m "Automated predictions update"
        git push
