name: Update Predictions

on:
  schedule:
    - cron: '0 12 * * *' # Executa todos os dias ao meio-dia (UTC)
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        working-directory: ./App
        run: |
          pip install -r requirements.txt
          pip install pandas numpy scipy scikit-learn gitpython gdown requests

      - name: Run update script
        working-directory: ./App
        run: python update_predictions.py

      - name: Commit and push changes
        working-directory: ./App
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          if [ -f data/latest_predictions.csv ]; then
            git add data/latest_predictions.csv
            if ! git diff --cached --quiet; then
              git commit -m "Automated predictions update [skip ci]"
              git push
            else
              echo "No changes to commit"
            fi
          else
            echo "File data/latest_predictions.csv does not exist. Skipping commit."